name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Backend install & lint
        working-directory: backend
        run: |
          npm ci
          npm run build --if-present || echo "No build step"
          npm test --if-present || echo "No tests yet"

      - name: Frontend install & build
        working-directory: frontend
        run: |
          npm ci
          npm run build

  deploy-frontend:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./frontend

  deploy-backend:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: render-oss/render-deploy-action@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}